### ISSUE TITLE
Use RST's "option lists" for, well, listing the options

### ISSUE THREAD

**Issue by cmarqu** [tox-dev/sphinx-argparse-cli#135]
I recently found that RST actually has direct support for command line option lists, as shown here
https://github.com/sphinx-themes/sphinx-themes.org/blob/f731beabab404bfe8f630baa28205b6871cf07e7/sample-docs/kitchen-sink/lists.rst?plain=1#L64-L86
which is rendered as e.g.
https://sphinx-themes.org/sample-sites/sphinx-rtd-theme/kitchen-sink/lists/#option-lists

**Comment by gaborbernat** [comment]
I find our implementation being much better, but thanks for the FYI 👍
