### ISSUE TITLE
Support rendering with argparse.RawDescriptionHelpFormatter 

### ISSUE THREAD

**Issue by mayrholu** [tox-dev/sphinx-argparse-cli#143]
It would be nice if sphix-arparse-cli could render formatted strings for epilogue or descriptions correctly. 

In argparse it is possible to set `formatter_class=argparse.RawDescriptionHelpFormatter` in the `ArgumentParser` (see https://docs.python.org/3/library/argparse.html#formatter-class) which renders the description strings as they are (when using """). In the sphinx-docs they unfortunately end up without proper formatting.

**Comment by gaborbernat** [comment]
A PR for this would be accepted 👍

**Comment by mayrholu** [comment]
@gaborbernat Thanks for the quick merge!
