### ISSUE TITLE
Support for Sphinx' program and option directives?

### ISSUE THREAD

**Issue by cmarqu** [tox-dev/sphinx-argparse-cli#40]
Hi,

I am wondering why this extension does not use the existing "standard" ``.. program::`` and ``.. option::`` directives of Sphinx (https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#directive-program)?
Could they be supported as well, or was it a conscious decision not to because of some limitation?

**Comment by gaborbernat** [comment]
When we discussed this those options did not come up, and we choose something else. Now I'd rather not have two ways to do things, so we'll keep the existing interface only.
